# Generated by Django 6.0.2 on 2026-03-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_categoria_produto_criado_em_alter_produto_ativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='url_imagem',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=250),
        ),
    ]
